version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app
      - ./bgm:/bgm:ro
    # LMStudioがホストマシンで動いてるから、
    # コンテナからホストにアクセスできるようにする
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload